#Base Image for the Build
FROM amazonlinux:2023 AS build-framework
# AS name of this build stage

RUN dnf update -y \
    && dnf install -y httpd

WORKDIR /var/www/html

COPY index.html /var/www/html


EXPOSE 80

CMD ["httpd", "-D", "FOREGROUND"]
                                                                                                                                                                                                                                                  